/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/doojMHvrdRI
 */
import Link from "next/link"

export function Header() {
  return (
    <header className="w-full py-4 md:py-6">
      <div className="container flex flex-col items-center gap-2 px-4 md:gap-4 md:flex-row md:justify-between">
        <div className="flex items-center space-x-2">
          <Link className="flex items-center space-x-2" href="#">
            <FlagIcon className="h-6 w-6" />
            <span className="font-bold tracking-tighter text-base">California Student Advisor</span>
          </Link>
        </div>
        <div className="flex items-center justify-end space-x-4 min-[300px]:space-x-2">
          <Link className="inline-flex items-center space-x-2 text-sm font-medium" href="#">
            Documentation
          </Link>
          <Link className="inline-flex items-center space-x-2 text-sm font-medium" href="#">
            OpenAPI Spec
          </Link>
        </div>
      </div>
    </header>
  )
}


function FlagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 4-1V3s-1 1-4 1-5-2-8-2-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}
